var S = [
  // ─── CHAPTER ───
  { t: 'ch', n: 'MIRACLE RANGERS', tt: '박사의 하루' },

  // ─── ACT 1: 연구소의 아침 (박사 1인칭) ───
  { t: 'bg', v: 'lab' },
  { t: 'n', tx: '아침.\n연구실에 혼자 남아 장치를 만지작거렸다.\n미라클 레인저들에게 더 도움이 되고 싶었다.\n\n이론상으로는 완벽한데...', ch: ['doc'] },
  { t: 'n', tx: '한 번만 더.\n이번엔 될지도 모른다.' },
  { t: 'pause', ms: 400 },
  { t: 'sfx', v: '치직!' },
  { t: 'fx', v: 'shake' },
  { t: 'n', tx: '...안 됐다.\n장치에서 연기가 피어올랐다. 출력이 너무 강했던걸까?' },
  { t: 'sfx', v: '에에엥—' },
  { t: 'fx', v: 'flash-red' },
  { t: 'n', tx: '\'위기감지 알림.\n연구소 내에 문제가 감지되었습니다.\'\n\n천장의 붉은 경고등이 점멸했다.' },
  { t: 'pause', ms: 500 },
  { t: 'n', tx: '그때 복도에서 연구실로 다가오는 발소리가 들렸다.', ch: ['red_sil'], lo: 'left' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"무슨 일이에요?"', ch: ['red_sil'], lo: 'left', tk: 'red_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"아~ 실험하다가 그만.\n금방 끌게용."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '...이번 달만 벌써 세 번째다.' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...이번에도 잘 안됐나보네요..\n박사님 밥 먹고하죠."', ch: ['red_sil'], lo: 'left', tk: 'red_sil' },
  { t: 'pause', ms: 500 },
  { t: 'n', tx: '다들 불러서 식당에 모였다.', ch: ['red_sil', 'black_sil', 'blue_sil', 'yellow_sil', 'pink_sil'], lo: 'spread' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"레드~ 특별히 많이 담아줬어!"', ch: ['yellow_sil', 'red_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"이 계란말이 진짜 맛있다!! 난 성공했어~!\n옐로가 만든 거예요, 박사님도 빨리 먹어요!!"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"아, 고마워용~"', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"박사님 연구는 잘 돼가고 있어?"', ch: ['blue_sil', 'doc'], lo: 'right', tk: 'blue_sil' },
  { t: 'n', tx: '...솔직히 잘 모르겠다.' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"글쎄용~\n거의 다 만들었어용."', ch: ['blue_sil', 'doc'], lo: 'right', tk: 'doc' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"기대되는걸?\n완성되면 알려줘."', ch: ['blue_sil'], lo: 'right', tk: 'blue_sil' },
  { t: 'pause', ms: 400 },
  { t: 'sfx', v: '에에엥— 에에엥—' },
  { t: 'fx', v: 'flash-red' },
  { t: 'n', tx: '또 경보가 울렸다.\n\n\'도시 내 위협 감지.\n카오스 공습 경보\'' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"가자"', ch: ['red_sil', 'black_sil', 'blue_sil', 'yellow_sil', 'pink_sil'], lo: 'spread', tk: 'red_sil' },
  { t: 'n', tx: '숟가락이 일제히 놓였다.' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"에— 나 아직 다 못 먹었는데!!"', ch: ['pink'], lo: 'left', tk: 'pink' },
  { t: 'd', sp: '블랙', cl: '#000000ff', tx: '"...돌아와서 먹어."', ch: ['black'], lo: 'left', tk: 'black' },
  { t: 'n', tx: '다섯 명의 뒷모습을 바라보고는... 모니터 앞에 앉았다.' },
  { t: 'pause', ms: 800 },

  // ─── ACT 2: 모니터 관전 → 카오스 등장 ───
  { t: 'bg', v: 'city' },
  { t: 'n', tx: '모니터에 현장 영상이 떴다.\n도심 한복판이었다.', ch: ['doc'] },
  { t: 'pause', ms: 500 },
  { t: 'sfx', v: '쾅!!' },
  { t: 'fx', v: 'shake' },
  { t: 'n', tx: '화면 속에서\n보라색 연기가 피어올랐다.' },
  { t: 'pause', ms: 500 },
  { t: 'bg', v: 'battle' },
  { t: 'pause', ms: 600 },
  { t: 'n', tx: '연기 속에서\n누군가가 걸어 나왔다.' },
  { t: 'pause', ms: 500 },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"기다리고 있었다.\n미라클 레인저."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"카오스!\n네놈들의 악행은 여기까지다!"', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red' },
  { t: 'n', tx: '레인저들이 전투 태세를 잡았다.\n모니터 앞에서 숨을 죽였다.' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"오늘은 좀 다를 거다.\n특별한 걸 준비해 왔거든."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'sfx', v: '쿠우웅!' },
  { t: 'fx', v: 'shake' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"나와라.\n다크 타이탄."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'n', tx: '모니터 화면이 일그러질 정도의 충격파.\n땅이 갈라지며 거대한 괴인이 나타났다.\n\n...이건 좀 다르다.', ch: ['titan'], lo: 'center', en: true },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"야, 이건 좀 다른데?\n크기가..."', ch: ['blue'], lo: 'left', tk: 'blue' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"상관없어.\n간다."', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red' },
  { t: 'pause', ms: 600 },

  // ─── ACT 3: 전투 — 밀린다 (모니터 관전) ───
  { t: 'bs', en: '다크 타이탄', eHp: 100, tHp: 100 },

  // TURN 1
  { t: 'n', tx: '나는 통신기를 잡았다.\n카오스의 신무기, 분석해내야 한다.', ch: ['doc'] },
  {
    t: 'q', tx: '통신기로 지시를 내린다.', fl: 't1', opts: [
      { tx: '⚔️ 블랙, 먼저 정찰 사격!', v: 'shoot' },
      { tx: '🛡️ 진형을 짜고 접근', v: 'form' },
      { tx: '✨ 선제 공격', v: 'rush' }
    ]
  },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"정찰 사격.\n...대상 포착."', ch: ['black'], lo: 'left', tk: 'black', if: { t1: 'shoot' } },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"진형 유지!\n천천히 접근한다."', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red', if: { t1: 'form' } },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"지금이다!\n달린다!"', ch: ['red'], lo: 'left', tk: 'red', if: { t1: 'rush' } },
  { t: 'pause', ms: 250 },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '팡!' },
  { t: 'n', tx: '블랙의 사격이 괴인에게 명중했다.\n\n...흠집 하나 나지 않았다.\n모니터를 두 번 확인했다.', ch: ['titan'], lo: 'center' },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"...안 통해."', ch: ['black'], lo: 'left', tk: 'black' },
  { t: 'pause', ms: 350 },
  { t: 'sfx', v: '쿵!!' },
  { t: 'fx', v: 'shake' },
  { t: 'bh', eHp: 97, tHp: 65 },
  { t: 'n', tx: '레인저들이 크게 날아갔다.\n\n나는 의자에서 벌떡 일어섰다.' },
  { t: 'n', tx: '...카오스의 기술력이 여기까지 올라온 건가.', ch: ['doc'] },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"어떤가.\n이번 괴인은 좀 다르지?"', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"...확실히 다르네."', ch: ['blue'], lo: 'left', tk: 'blue' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"여유가 있군.\n한 번 더 맞으면 사라질 여유다."', ch: ['chaos'], lo: 'right', tk: 'chaos' },

  // TURN 2
  {
    t: 'q', tx: '다시 지시한다.', fl: 't2', opts: [
      { tx: '✨ 옐로, 썬더 크러쉬!', v: 'thunder' },
      { tx: '⚔️ 블루와 옐로의 협공', v: 'combo' }
    ]
  },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"썬더 크러쉬~!"', ch: ['yellow'], lo: 'left', tk: 'yellow', if: { t2: 'thunder' } },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"옐로, 타이밍 맞춰!"', ch: ['blue', 'yellow'], lo: 'left', tk: 'blue', if: { t2: 'combo' } },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"알겠어~!\n같이 간다!"', ch: ['blue', 'yellow'], lo: 'left', tk: 'yellow', if: { t2: 'combo' } },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '슈아앗!' },
  { t: 'n', tx: '옐로의 번개가 괴인을 감쌌다.\n하지만—', if: { t2: 'thunder' } },
  { t: 'n', tx: '블루의 돌진과 옐로의 번개가\n동시에 괴인을 덮쳤다.\n하지만—', if: { t2: 'combo' } },
  { t: 'n', tx: '다크 타이탄이 번개를\n맨손으로 흩어버렸다.\n\n말이 안 된다.\n옐로의 썬더 크러쉬도 효과가 없는 것인가.', ch: ['titan'], lo: 'center' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"뭐?!\n썬더 크러쉬가 안 먹혀?!"', ch: ['pink'], lo: 'left', tk: 'pink' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"...무의미하다."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'sfx', v: '퍽!!' },
  { t: 'fx', v: 'shake' },
  { t: 'bh', eHp: 93, tHp: 35 },
  { t: 'n', tx: '다크 타이탄의 주먹이\n레인저들을 강타했다.\n\n나는 모니터 앞에서 주먹을 쥐었다.' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"다들 버텨~!"', ch: ['yellow'], lo: 'left', tk: 'yellow' },

  // TURN 3 - 절체절명
  {
    t: 'q', tx: '포기할 수 없다.', fl: 't3', opts: [
      { tx: '⚔️ 필살기!', v: 'allin' },
      { tx: '✨ 다섯 명의 합체 공격!', v: 'unite' }
    ]
  },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"이걸로... 끝낸다—!"', ch: ['red'], lo: 'left', tk: 'red', if: { t3: 'allin' } },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"다 같이!\n하나로 모은다—!"', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red', if: { t3: 'unite' } },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '슈아아앗!!' },
  { t: 'pause', ms: 500 },
  { t: 'n', tx: '레드의 대검이 괴인의 가슴팍에\n꽂혔다.\n\n...그런 줄 알았다.', if: { t3: 'allin' } },
  { t: 'n', tx: '다섯 명의 힘이 하나로 모여\n괴인에게 쏟아졌다.\n\n...그런 줄 알았다.', if: { t3: 'unite' } },
  { t: 'n', tx: '다크 타이탄이 대검을\n맨손으로 잡아 멈춰 세웠다.', ch: ['titan'], lo: 'center', if: { t3: 'allin' } },
  { t: 'n', tx: '다크 타이탄이 합체 공격을\n한 손으로 튕겨냈다.', ch: ['titan'], lo: 'center', if: { t3: 'unite' } },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...!"', ch: ['red'], lo: 'left', tk: 'red' },
  { t: 'pause', ms: 300 },
  { t: 'sfx', v: '쾅!!' },
  { t: 'fx', v: 'shake' },
  { t: 'bh', eHp: 90, tHp: 10 },
  { t: 'n', tx: '다크 타이탄의 일격.\n레인저 전원이 쓰러졌다.\n\n숨이 멎는 것 같았다.', ch: ['titan'], lo: 'center' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"끝이다.\n더는 일어나지 못할 거다."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'n', tx: '모니터 속 다섯 명이\n일어서지 못하고 있었다.\n\n손이 떨렸다.', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"...야, 이거 진짜 좀 위험한데."', ch: ['blue'], lo: 'left', tk: 'blue' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"아직... 아직이다...!"', ch: ['red'], lo: 'left', tk: 'red' },
  { t: 'n', tx: '레드가 대검을 짚고\n간신히 무릎을 세웠다.\n\n하지만 다시 쓰러졌다.' },
  { t: 'pause', ms: 800 },
  { t: 'n', tx: '작업대 위의 장치가 눈에 들어왔다.\n미완성. 아직 테스트도 못 한 시제품.\n\n...하지만.', ch: ['doc'] },

  // ─── ACT 4: 박사의 결단 ───
  {
    t: 'q', tx: '', fl: 'go', opts: [
      { tx: '▶ 가야 한다.', v: 'go' },
      { tx: '▶ 이대로 보고만 있을 수 없다.', v: 'go2' }
    ]
  },
  { t: 'n', tx: '장치를 움켜쥐고 뛰쳐나갔다.\n복도를 지나 격납고로 향했다.' },
  { t: 'n', tx: '그리고는 오렛동안 사용하지 않았던 스쿠터에 올라탔다.' },
  { t: 'pause', ms: 700 },
  { t: 'sfx', v: '부우웅!' },
  { t: 'n', tx: '현장에 도착했을 때,\n다섯 명은 쓰러져 있었고\n카오스는 웃고 있었다.\n\n...아직 늦지 않았다.' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"여러분!\n포기하지 마세용!"', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"박사님?!"', ch: ['pink', 'yellow'], lo: 'left', tk: 'pink' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"바..박사?..!!"', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"미라클 부스터...\n아직 테스트도 못 했지만..."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '손이 떨렸다.\n그래도 저 아이들 앞에서\n가만히 있을 수는 없었다.' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"지금은 이것밖에 없어용.\n여러분을 믿을게용!"', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '장치를 하늘로 던졌다.' },
  { t: 'pause', ms: 500 },
  { t: 'fx', v: 'flash-white' },
  { t: 'drama', lines: ['미라클 부스터'], cls: 'gold' },
  { t: 'pause', ms: 800 },
  { t: 'fx', v: 'shake' },
  { t: 'drama', lines: ['기 동 합 니 다'], cls: 'gold large' },
  { t: 'pause', ms: 900 },
  { t: 'fx', v: 'flash-white' },
  { t: 'pause', ms: 200 },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '쉬이이잇!!' },
  { t: 'fx', v: 'shake' },
  { t: 'pause', ms: 800 },
  { t: 'drama', lines: ['에너지 증폭률'], cls: 'gold' },
  { t: 'pause', ms: 600 },
  { t: 'drama', lines: ['1 0 0 0 %'], cls: 'gold large' },
  { t: 'pause', ms: 500 },
  { t: 'fx', v: 'flash-gold' },
  { t: 'fx', v: 'shake' },
  { t: 'bgm', v: 'battle2' },
  { t: 'boost' },
  { t: 'n', tx: '눈부신 빛이 레인저들을 감쌌다.\n부서진 갑옷이 조금씩 재생되고,\n금빛 기운이 타올랐다.\n\n작동했다. 작동한 거다.' },
  { t: 'pause', ms: 500 },
  { t: 'bh', eHp: 90, tHp: 100 },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"이 힘은...!"', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"새로운 발명품이에용!\n그것보다 저 녀석부터!"', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...박사님. 고마워요.\n다시 간다!"', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"그까짓 장난감 하나로\n뭐가 달라지겠—"', ch: ['chaos'], lo: 'right', tk: 'chaos' },

  // ─── ACT 5: 역전 ───
  {
    t: 'q', tx: '부스터의 힘으로!', fl: 't4', opts: [
      { tx: '⚔️ 파이널 스트라이크!', v: 'chain' },
      { tx: '✨ 전원 돌격!', v: 'all' }
    ]
  },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"순서대로 간다.\n...이번엔 다르다."', ch: ['black'], lo: 'left', tk: 'black', if: { t4: 'chain' } },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"전원 돌격!\n한 번에 끝낸다!"', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red', if: { t4: 'all' } },
  { t: 'pause', ms: 300 },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '팡팡팡!' },
  { t: 'fx', v: 'shake' },
  { t: 'n', tx: '블랙의 강화된 사격이\n다크 타이탄의 장갑을 관통했다!\n\n통했다...!', ch: ['titan'], lo: 'center' },
  { t: 'bh', eHp: 65, tHp: 100 },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"뭐, 뭐?!"', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"자, 내 차례다."', ch: ['blue'], lo: 'left', tk: 'blue' },
  { t: 'pause', ms: 300 },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '슈앗!' },
  { t: 'fx', v: 'shake' },
  { t: 'n', tx: '블루의 잔상이 세 개로 갈라졌다.\n괴인의 옆구리에서 불꽃이 튀었다!' },
  { t: 'bh', eHp: 45, tHp: 100 },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"이 힘이라면~!\n썬더 크러쉬!"', ch: ['yellow'], lo: 'left', tk: 'yellow' },
  { t: 'pause', ms: 300 },
  { t: 'fx', v: 'flash-white' },
  { t: 'sfx', v: '쾌쾌쾌광!' },
  { t: 'fx', v: 'shake' },
  { t: 'n', tx: '강화된 번개가 하늘에서 내리꽂혔다!\n\n다크 타이탄이 처음으로 비명을 질렀다!', ch: ['titan'], lo: 'center' },
  { t: 'bh', eHp: 25, tHp: 100 },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"내가 묶어둘게!!\n레드, 지금이야!!"', ch: ['pink', 'red'], lo: 'sides', tk: 'pink' },
  { t: 'pause', ms: 200 },
  { t: 'fx', v: 'flash-white' },
  { t: 'n', tx: '핑크의 채찍이\n다크 타이탄을 속박했다.\n\n다섯 명의 공격이 하나로 모인다.' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"이럴 리가...!"', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'n', tx: '다섯 개의 색이 하나로 모이고 있었다.', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread' },

  // 피니시
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"끝이다, 카오스."', ch: ['red'], lo: 'left', tk: 'red' },
  { t: 'pause', ms: 600 },
  { t: 'drama', lines: ['미라클'], cls: 'red' },
  { t: 'pause', ms: 500 },
  { t: 'drama', lines: ['파이널 스트라이크!'], cls: 'red large' },
  { t: 'pause', ms: 500 },
  { t: 'fx', v: 'flash-white' },
  { t: 'pause', ms: 200 },
  { t: 'fx', v: 'flash-gold' },
  { t: 'pause', ms: 200 },
  { t: 'sfx', v: '펑!!!' },
  { t: 'fx', v: 'flash-white' },
  { t: 'fx', v: 'shake' },
  { t: 'pause', ms: 300 },
  { t: 'fx', v: 'flash-white' },
  { t: 'fx', v: 'shake' },
  { t: 'bh', eHp: 0, tHp: 100 },
  { t: 'pause', ms: 1200 },
  { t: 'be' },
  { t: 'n', tx: '다크 타이탄은 빛 속에서 소멸했다.\n\n이겼다.\n이긴 거다.', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread' },
  { t: 'pause', ms: 700 },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"미라클 레인저...\n오늘은 졌다."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"아, 또 도망가네?"', ch: ['blue'], lo: 'left', tk: 'blue' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"네놈! 전략적 후퇴라고 했을 텐데."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"이번에는 놓치지 않겠다~!"', ch: ['yellow'], lo: 'left', tk: 'yellow' },
  { t: 'd', sp: '카오스', cl: '#ce93d8', tx: '"...다음에는 없을 거다.\n두고 보자, 미라클 레인저."', ch: ['chaos'], lo: 'right', tk: 'chaos' },
  { t: 'n', tx: '모두가 카오스를 잡으려고 달려들었지만\n카오스는 희미해지며 연기 속으로 사라졌다.' },
  { t: 'pause', ms: 800 },
  { t: 'bg', v: 'city' },
  { t: 'n', tx: '그때, 멀리서 환호가 들려왔다.\n처음엔 작게, 그리고 점점 크게.', ch: ['doc'] },
  { t: 'n', tx: '"미라클 레인저다!"\n"이겼다!"\n\n멀리서 사람들의 함성이 들렸다.' },
  { t: 'n', tx: '레인저들이 손을 흔들었다.\n나는 조용히 그들에게서 멀리 떨어졌다.', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread' },
  { t: 'n', tx: '블루는 옐로의 팔에 난\n상처를 발견했다.' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"여기 다쳤잖아.\n나중에 치료 받아."', ch: ['blue', 'yellow'], lo: 'left', tk: 'blue' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"에이~ 이 정도 괜찮아~"', ch: ['blue', 'yellow'], lo: 'left', tk: 'yellow' },
  { t: 'pause', ms: 600 },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"옐로 괜찮아?!\n아까 엄청 세게 맞았잖아!!"', ch: ['pink', 'yellow'], lo: 'left', tk: 'pink' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"괜찮다니까~\n잘 쉬면 금방 나을 거야!"', ch: ['pink', 'yellow'], lo: 'left', tk: 'yellow' },
  { t: 'pause', ms: 400 },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...다들 돌아가자.\n오늘은 충분히 싸웠어."', ch: ['red', 'black', 'blue', 'yellow', 'pink'], lo: 'spread', tk: 'red' },
  { t: 'n', tx: '레드가 앞장서서 걸어갔다.\n하나둘 뒤를 따랐다.' },
  { t: 'pause', ms: 600 },
  { t: 'n', tx: '나도 스쿠터에 올라타\n연구소로 향했다.\n\n석양이 도시를 물들이고 있었다.', ch: ['doc'] },
  { t: 'pause', ms: 1000 },

  // ─── ACT 6: 연구소 저녁 ───
  { t: 'ch', n: '', tt: '그날 저녁' },
  { t: 'bg', v: 'lab-ev' },
  { t: 'n', tx: '연구소로 돌아왔다.\n전투의 흥분이 채 가시지 않은 저녁.', ch: ['doc'] },
  { t: 'n', tx: '다행히...모두 무사하다.\n좋아.' },
  { t: 'sfx', v: '에에엥—' },
  { t: 'fx', v: 'flash-red' },
  { t: 'n', tx: '\'위기감지 알림.\n연구소 내에 문제가 감지되었습니다.\'' },
  { t: 'n', tx: '우리가 들어서자 마자 발생한 알림. 아무래도 부스터의 출력이 너무 강한 탓에 이상 현상으로 인식하는 듯 했다.', ch: ['doc'] },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"박사님!? 설마 카오스가..!"', ch: ['red_sil'], lo: 'left', tk: 'red_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"아.. 아닐거에용. 부스터 출력이 너무 강했나보네용.\n출력 조정하면 괜찮을 거예용."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"박사님 덕분이에요.\n...고마워요."', ch: ['red_sil'], lo: 'left', tk: 'red_sil' },
  { t: 'n', tx: '레드가 짧게 고개를 숙였다.' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"아니에용.\n다들 포기하지 않았으니까용."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '사실 겁이 났다.\n장치가 안 되면 어쩌나.\n내가 가서 뭘 할 수 있나.\n\n...그런 말은 하지 않았다.' },
  { t: 'pause', ms: 600 },

  // ── 블랙 ──
  { t: 'n', tx: '복도를 걷다가 블랙과 마주쳤다.\n흡연실 쪽에서 걸어오고 있었다.\n희미한 담배 냄새가 났다.', ch: ['black_sil'], lo: 'right' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"블랙, 오늘 수고했어용."', ch: ['doc', 'black_sil'], lo: 'sides', tk: 'doc' },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"...박사님도."', ch: ['black_sil'], lo: 'right', tk: 'black_sil' },
  { t: 'pause', ms: 600 },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"...고마웠어."', ch: ['black_sil'], lo: 'right', tk: 'black_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"에? 뭐가용?"', ch: ['doc', 'black_sil'], lo: 'sides', tk: 'doc' },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"뛰어온 거."', ch: ['black_sil'], lo: 'right', tk: 'black_sil' },
  {
    t: 'q', tx: '', fl: 'bk_r', opts: [
      { tx: '▶ "무서웠는데... 가만히 있을 수가 없었어용."', v: 'scared' },
      { tx: '▶ "블랙이 버텨줬으니까용."', v: 'thanks' }
    ]
  },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"......그래."', ch: ['black_sil'], lo: 'right', tk: 'black_sil' },
  { t: 'aff', tx: '블랙의 호감도가 올랐다', dir: 'up' },
  { t: 'n', tx: '블랙이 주머니에 손을 넣고 걸어갔다.\n\n...나쁘지 않았다.' },
  { t: 'pause', ms: 800 },

  // ── 레드 ──
  { t: 'n', tx: '옥상으로 올라갔다.\n레드가 혼자 야경을 바라보고 있었다.', ch: ['red_sil'], lo: 'right' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...오늘은 위험했어요.\n새로운 방식이 필요해.."', ch: ['red_sil'], lo: 'right', tk: 'red_sil' },
  { t: 'n', tx: '레드가 난간에 기대며 말했다.' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...내가 리더인데...\n모두를 위험에..."', ch: ['red_sil'], lo: 'right', tk: 'red_sil' },
  {
    t: 'q', tx: '', fl: 'red_r', opts: [
      { tx: '▶ "레드가 리더라서 다행이에용."', v: 'courage' },
      { tx: '▶ "잘 하고 있어용."', v: 'together' }
    ]
  },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...위로해줘서 고마워요."', ch: ['red_sil'], lo: 'right', tk: 'red_sil' },
  { t: 'aff', tx: '레드의 호감도가 올랐다', dir: 'up' },
  { t: 'n', tx: '레드가 피식 웃었다.' },
  { t: 'pause', ms: 800 },

  // ── 블루 ──
  { t: 'n', tx: '작전실을 지나가는데\n블루를 마주쳤다.', ch: ['blue_sil'], lo: 'right' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"오늘 박사님 덕분에 살았어"', ch: ['blue_sil'], lo: 'right', tk: 'blue_sil' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"다음엔 더 빠르게 움직이고 싶어.\n박사님, 출력 한계를 더 올릴 수 있어?"', ch: ['blue_sil'], lo: 'right', tk: 'blue_sil' },
  { t: 'n', tx: '블루의 눈이 반짝이고 있었다.' },
  {
    t: 'q', tx: '', fl: 'blu_r', opts: [
      { tx: '▶ "다음엔 더 올려볼게용. 기대하셔도 돼용."', v: 'dunno' },
      { tx: '▶ "블루가 강하니까 가능한 거예용."', v: 'praise' }
    ]
  },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"...고마워.\n다음엔 보여줄게."', ch: ['blue_sil'], lo: 'right', tk: 'blue_sil' },
  { t: 'aff', tx: '블루의 호감도가 올랐다', dir: 'up' },
  { t: 'n', tx: '블루가 희미하게 미소 지었다.' },
  { t: 'pause', ms: 800 },

  // ── 핑크+옐로 ──
  { t: 'n', tx: '휴게실에서 웃음소리가 들렸다.\n핑크가 과자 봉지를 들고 돌아다니고 있었다.', ch: ['pink_sil', 'yellow_sil'], lo: 'left' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"아 블랙한테도 줬는데\n안 받더라"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"그건 블랙이 단 거 싫어하니까~"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"초콜릿은 먹던걸?\n어제 작전실에서 블랙이 몰래\n초콜릿 먹는 거 봤다구!!"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"아 그런가..? 아무튼 내가 많이 먹을게~"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"아 박사님 안녕~!\n박사님이 도와주러 왔을 때\n완전 멋있었어!!"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"맞아~ 완전 영화 같았어.\n\'여러분, 포기하지 마세용!\'\n하면서~"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'n', tx: '...그렇게 흉내 내지 않아도 되는데.' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"진짜 죽나 싶었다니까..\n진짜 무서웠다구!"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  {
    t: 'q', tx: '', fl: 'yp_r', opts: [
      { tx: '▶ "앞으로도 저만 믿으세요"', v: 'forever' },
      { tx: '▶ "제가 도움을 줄 수 있어서 다행이에용"', v: 'funny' }
    ]
  },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"박사님이 있어서\n정말 다행이야~"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"다음에도 박사님이\n달려와 줄 거지?!"', ch: ['pink_sil', 'yellow_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'aff', tx: '핑크와 옐로의 호감도가 올랐다', dir: 'up' },
  { t: 'n', tx: '둘의 웃음이 복도에 퍼졌다.\n나도 따라 웃음이 나왔다.' },
  { t: 'pause', ms: 1200 },

  // ─── ACT 7: 밤 ───
  { t: 'bg', v: 'night' },
  { t: 'n', tx: '밤이 깊어졌다.\n연구소의 불이 하나둘 꺼져갔다.', ch: ['doc'] },
  { t: 'n', tx: '회의실\n레인저들이 각자 방으로 향하려 했다.', ch: ['red_sil', 'black_sil', 'blue_sil', 'yellow_sil', 'pink_sil'], lo: 'spread' },
  { t: 'd', sp: '핑크', cl: '#f48fb1', tx: '"다들 수고!!\n내일도 파이팅이야!!"', ch: ['pink_sil'], lo: 'left', tk: 'pink_sil' },
  { t: 'd', sp: '블랙', cl: '#999', tx: '"...푹 쉬어."', ch: ['black_sil'], lo: 'right', tk: 'black_sil' },
  { t: 'd', sp: '옐로', cl: '#ffd54f', tx: '"잘 자~"', ch: ['yellow_sil'], lo: 'left', tk: 'yellow_sil' },
  { t: 'd', sp: '블루', cl: '#42a5f5', tx: '"내일 봐."', ch: ['blue_sil'], lo: 'right', tk: 'blue_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"다들 수고했어용~\n푹 쉬세용."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '하나둘 자기 방으로 들어갔다.' },
  { t: 'n', tx: '레드가 마지막으로 남았다.\n잠시 서서 기지개를 켰다.' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...박사님도 푹 쉬어요. 아 그리고..."', ch: ['red_sil'], lo: 'right', tk: 'red_sil' },
  { t: 'd', sp: '레드', cl: '#e53935', tx: '"...아뇨 다음에 얘기할게요."', ch: ['red_sil'], lo: 'right', tk: 'red_sil' },
  { t: 'd', sp: '박사', cl: '#9575cd', tx: '"그래용. 언제든지 편하게 말해줘용."', ch: ['doc'], lo: 'right', tk: 'doc' },
  { t: 'n', tx: '짧게 손 흔들고 방으로 들어갔다.' },
  { t: 'pause', ms: 1200 },
  { t: 'n', tx: '나도 내 방으로 돌아왔다.\n카드키를 찍고 안으로 들어섰다.\n문이 닫히고, 크게 한숨을 내쉬었다.', ch: ['doc'] },
  { t: 'n', tx: '그리고는 침대에 누워, 천장을 바라봤다.' },
  { t: 'n', tx: '오늘 정말로 위험했지만, 모두 무사할 수 있었다.' },
  { t: 'pause', ms: 1500 },
  { t: 'drama', lines: ['앞으로도 계속 평범한 하루가 되기를 바란다.'], cls: '' },
  { t: 'end' }
];
